import * as z from 'zod/mini';
import { IntBool, StringFalse, StringTrue } from '../../schemas.ts';
import { Image } from './shared.ts';

const Feature = z.strictObject({
	name: z.nullable(z.string()),
	value: z.nullable(z.string()),
	id_feature: z.string(),
	position: z.string(),
});

const Attribute = z.strictObject({
	id_attribute: z.string(),
	id_attribute_group: z.string(),
	name: z.string(),
	group: z.string(),
	reference: z.string(),
	ean13: z.string(),
	isbn: z.literal(''),
	upc: z.literal(''),
	mpn: z.literal(''),
});

const SpecificPrices = z.strictObject({
	id_specific_price: z.string(),
	id_specific_price_rule: z.string(),
	id_cart: z.string(),
	id_product: z.string(),
	id_shop: z.literal('1'),
	id_shop_group: z.string(),
	id_currency: z.literal('0'),
	id_country: z.literal('0'),
	id_group: z.literal('0'),
	id_customer: z.literal('0'),
	id_product_attribute: z.string(),
	price: z.string(),
	from_quantity: z.literal('1'),
	reduction: z.string(),
	reduction_tax: z.literal('1'),
	reduction_type: z.string(),
	from: z.string(),
	to: z.string(),
	score: z.string(),
});

export const ProductDetails = z.strictObject({
	id_shop_default: StringTrue,
	id_manufacturer: StringFalse,
	id_supplier: StringFalse,
	reference: z.string(),
	is_virtual: StringFalse,
	delivery_in_stock: z.literal(''),
	delivery_out_stock: z.literal(''),
	id_category_default: z.string(),
	on_sale: StringFalse,
	online_only: StringFalse,
	ecotax: z.literal(0),
	minimal_quantity: z.union([z.string(), z.number()]),
	low_stock_threshold: z.null(),
	low_stock_alert: StringFalse,
	price: z.string(),
	unity: z.literal(''),
	unit_price_ratio: z.literal('0.000000'),
	additional_shipping_cost: z.literal('0.000000'),
	customizable: StringFalse,
	text_fields: StringFalse,
	uploadable_files: StringFalse,
	redirect_type: z.enum(['', '301-category']),
	id_type_redirected: StringFalse,
	available_for_order: StringTrue,
	available_date: z.nullable(z.string()),
	show_condition: StringFalse,
	condition: z.literal('new'),
	show_price: StringTrue,
	indexed: z.union([StringFalse, StringTrue]),
	visibility: z.literal('both'),
	cache_default_attribute: z.string(),
	advanced_stock_management: StringFalse,
	date_add: z.string(),
	date_upd: z.string(),
	pack_stock_type: z.literal('3'),
	meta_description: z.literal(''),
	meta_keywords: z.literal(''),
	meta_title: z.literal(''),
	link_rewrite: z.string(),
	name: z.string(),
	description: z.string(),
	description_short: z.string(),
	available_now: z.literal(''),
	available_later: z.string(),
	id: z.number(),
	id_product: z.number(),
	out_of_stock: z.union([z.literal(0), z.literal(1), z.literal(2)]),
	new: IntBool,
	id_product_attribute: z.number(),
	quantity_wanted: z.literal(1),
	extraContent: z.tuple([]),
	allow_oosp: IntBool,
	category: z.string(),
	category_name: z.string(),
	link: z.string(),
	attribute_price: z.number().check(z.nonnegative()),
	price_tax_exc: z.number().check(z.positive()),
	price_without_reduction: z.number().check(z.positive()),
	reduction: z.number(),
	specific_prices: z.union([SpecificPrices, z.tuple([]), z.boolean()]),
	quantity: z.int().check(z.nonnegative()),
	quantity_all_versions: z.int(),
	id_image: z.string(),
	features: z.array(Feature),
	attachments: z.tuple([]),
	virtual: z.literal(0),
	pack: z.literal(0),
	packItems: z.tuple([]),
	nopackprice: z.literal(0),
	customization_required: z.literal(false),
	attributes: z.optional(z.record(z.string(), Attribute)),
	rate: z.literal(0),
	tax_name: z.literal(''),
	ecotax_rate: z.number(),
	unit_price: z.string(),
	customizations: z.object({
		fields: z.tuple([]),
	}),
	id_customization: z.number(),
	is_customizable: z.literal(false),
	show_quantities: z.literal(false),
	quantity_label: z.enum(['Item', 'Items']),
	quantity_discounts: z.tuple([]),
	customer_group_discount: z.number(),
	images: z.array(Image),
	cover: Image,
	has_discount: z.boolean(),
	discount_type: z.nullable(z.literal('percentage')),
	discount_percentage: z.nullable(z.string()),
	discount_percentage_absolute: z.nullable(z.string()),
	discount_amount: z.nullable(z.string()),
	discount_amount_to_display: z.nullable(z.string()),
	price_amount: z.number().check(z.nonnegative()),
	unit_price_full: z.literal(''),
	show_availability: z.literal(true),
	availability_date: z.nullable(z.string()),
	availability_message: z.string(),
	availability: z.enum(['available', 'unavailable', 'last_remaining_items']),
});
export type ProductDetails = z.infer<typeof ProductDetails>;
