import * as z from 'zod/mini';
import { Image } from './shared.ts';

const Feature = z.object({
	name: z.string(),
	value: z.string(),
	id_feature: z.string(),
	position: z.string(),
});

const Attribute = z.object({
	id_attribute: z.string(),
	id_attribute_group: z.string(),
	name: z.string(),
	group: z.string(),
	reference: z.string(),
	ean13: z.string(),
	isbn: z.string(),
	upc: z.string(),
	mpn: z.string(),
});

const SpecificPrices = z.object({
	id_specific_price: z.string(),
	id_specific_price_rule: z.string(),
	id_cart: z.string(),
	id_product: z.string(),
	id_shop: z.string(),
	id_shop_group: z.string(),
	id_currency: z.string(),
	id_country: z.string(),
	id_group: z.string(),
	id_customer: z.string(),
	id_product_attribute: z.string(),
	price: z.string(),
	from_quantity: z.string(),
	reduction: z.string(),
	reduction_tax: z.string(),
	reduction_type: z.string(),
	from: z.string(),
	to: z.string(),
	score: z.string(),
});

export const ProductDetails = z.object({
	id_shop_default: z.string(),
	id_manufacturer: z.string(),
	id_supplier: z.string(),
	reference: z.string(),
	is_virtual: z.string(),
	delivery_in_stock: z.string(),
	delivery_out_stock: z.string(),
	id_category_default: z.string(),
	on_sale: z.string(),
	online_only: z.string(),
	ecotax: z.number(),
	minimal_quantity: z.string(),
	low_stock_threshold: z.null(),
	low_stock_alert: z.string(),
	price: z.string(),
	unity: z.string(),
	unit_price_ratio: z.string(),
	additional_shipping_cost: z.string(),
	customizable: z.string(),
	text_fields: z.string(),
	uploadable_files: z.string(),
	redirect_type: z.string(),
	id_type_redirected: z.string(),
	available_for_order: z.string(),
	available_date: z.string(),
	show_condition: z.string(),
	condition: z.string(),
	show_price: z.string(),
	indexed: z.string(),
	visibility: z.string(),
	cache_default_attribute: z.string(),
	advanced_stock_management: z.string(),
	date_add: z.string(),
	date_upd: z.string(),
	pack_stock_type: z.string(),
	meta_description: z.string(),
	meta_keywords: z.string(),
	meta_title: z.string(),
	link_rewrite: z.string(),
	name: z.string(),
	description: z.string(),
	description_short: z.string(),
	available_now: z.string(),
	available_later: z.string(),
	id: z.number(),
	id_product: z.number(),
	out_of_stock: z.number(),
	new: z.number(),
	id_product_attribute: z.number(),
	quantity_wanted: z.number(),
	extraContent: z.array(z.unknown()),
	allow_oosp: z.number(),
	category: z.string(),
	category_name: z.string(),
	link: z.string(),
	attribute_price: z.number(),
	price_tax_exc: z.number(),
	price_without_reduction: z.number(),
	reduction: z.number(),
	specific_prices: SpecificPrices,
	quantity: z.number(),
	quantity_all_versions: z.number(),
	id_image: z.string(),
	features: z.array(Feature),
	attachments: z.array(z.unknown()),
	virtual: z.number(),
	pack: z.number(),
	packItems: z.array(z.unknown()),
	nopackprice: z.number(),
	customization_required: z.boolean(),
	attributes: z.record(z.string(), Attribute),
	rate: z.number(),
	tax_name: z.string(),
	ecotax_rate: z.number(),
	unit_price: z.string(),
	customizations: z.object({
		fields: z.array(z.unknown()),
	}),
	id_customization: z.number(),
	is_customizable: z.boolean(),
	show_quantities: z.boolean(),
	quantity_label: z.string(),
	quantity_discounts: z.array(z.unknown()),
	customer_group_discount: z.number(),
	images: z.array(Image),
	cover: Image,
	has_discount: z.boolean(),
	discount_type: z.string(),
	discount_percentage: z.string(),
	discount_percentage_absolute: z.string(),
	discount_amount: z.string(),
	discount_amount_to_display: z.string(),
	price_amount: z.number(),
	unit_price_full: z.string(),
	show_availability: z.boolean(),
	availability_date: z.null(),
	availability_message: z.string(),
	availability: z.string(),
});
